######################################################################
#  Project Makefile
######################################################################

.PSEUDO: all front clean clobber flash flash_front flash_rear

all:
	$(MAKE) -f Makefile.main -$(MAKEFLAGS)

clean:
	$(MAKE) -f Makefile.main -$(MAKEFLAGS) clean

clobber:
	$(MAKE) -f Makefile.main -$(MAKEFLAGS) clobber

flash:
	$(MAKE) -f Makefile.main -$(MAKEFLAGS) flash


